import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

export type Language = 'zh' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 翻译文件
const translations: Record<Language, Record<string, string>> = {
  zh: {
    // 导航
    'nav.game': '游戏',
    'nav.history': '战绩殿堂',
    'nav.rules': '游戏指南',
    
    // 导航栏
    'navbar.brandName': '王牌博弈',
    'navbar.tagline': 'GAMEFI · 燃烧通缩协议',
    'navbar.unclaimed': '待领取',
    'navbar.unclaimedReward': '待领取奖励',
    'navbar.claim': '领取',
    'navbar.claimNow': '立即领取',
    'navbar.claimSuccess': '成功领取 {amount} BNB!',
    'navbar.claimFailed': '领取失败，请重试',
    
    // VRF等待
    'vrf.waiting': '等待链上确认',
    'vrf.timeout': '等待超时',
    'vrf.generating': 'Chainlink VRF正在生成可验证随机数',
    'vrf.maybeStuck': 'VRF回调可能卡住了，可尝试取消请求',
    'vrf.usually': '通常需要 10-30 秒',
    'vrf.cancel': '取消请求',
    'vrf.doNotClose': '请勿关闭页面，结果将自动更新',
    'vrf.formatMin': '{min}分{sec}秒',
    'vrf.formatSec': '{sec}秒',
    
    // 成功动画
    'success.arrived': '到账成功！',
    'success.afterFee': '(扣除5%手续费后)',
    'success.autoTransfer': '💡 奖励已通过内部交易自动转入，余额已增加',
    
    // 奖励阶梯
    'ladder.title': '奖励阶梯',
    'ladder.currentLevel': '当前等级',
    'ladder.maxStreak': '最高 {n} 连胜',
    'ladder.maxWin': '最高可赢',
    'ladder.pool': '奖池',
    'ladder.nonCumulative': '（非累进，替换式）',
    'ladder.nStreak': '{n}连胜',
    'ladder.needHigher': '需更高等级',
    'ladder.currentCashout': '当前可兑现',
    'ladder.level': '等级',
    
    // 水平奖励
    'hreward.title': '奖励阶梯',
    'hreward.currentLevel': '当前等级:',
    'hreward.maxStreakLabel': '(最高{n}连胜)',
    'hreward.currentStreak': '当前连胜',
    'hreward.streakCount': '连胜次数',
    'hreward.currentReward': '当前奖励',
    'hreward.nextTarget': '下一目标',
    'hreward.winMore': '再赢1局 → {n}连胜',
    'hreward.reachedMax': '🎉 已达上限',
    'hreward.upgradeUnlock': '升级门槛解锁更高',
    'hreward.entryZone': '入门区',
    'hreward.advancedZone': '进阶区',
    'hreward.eliteZone': '精英区',
    'hreward.legendZone': '传奇区',
    'hreward.streakRange1': '1-5连胜',
    'hreward.streakRange2': '6-10连胜',
    'hreward.streakRange3': '11-15连胜',
    'hreward.streakRange4': '16-20连胜',
    'hreward.yourMaxTarget': '您的最高目标 ({tier}等级):',
    'hreward.nStreakEquals': '{n}连胜 = {percent}%',
    'hreward.percentDetail': '📊 奖励百分比详解（占当前奖池比例）',
    'hreward.exampleNote': '💡 举例说明：若当前奖池为 1 BNB，你连胜5次后收手，可获得 0.25% × 1 BNB = 0.0025 BNB（扣除5%手续费后实际到账 0.002375 BNB）',
    'hreward.ruleNote': '💡 <strong>规则说明</strong>: 每次猜对+1连胜，奖励随连胜数增加（非累加，达到几连胜就按对应比例领取）',
    'hreward.cashoutTip': '🎯 随时可点「收手」领取当前奖励 · 猜错则失去所有累积',
    
    // 首页标签
    'home.tag.symbols': '5符号匹配',
    'home.tag.payline': '中间行赔付',
    'home.tag.symbolCount': '10种符号',
    'home.tag.return': '100% 返还',
    
    // 合约地址
    'contract.game': '游戏合约',
    'contract.token': '代币合约',
    'contract.copy': '复制地址',
    'contract.view': '在BSCScan查看',
    'contract.copied': '地址已复制',
    'contract.pending': '待部署...',
    'contract.gameContractCopied': '游戏合约地址已复制!',
    'contract.tokenContractCopied': '代币合约地址已复制!',
    
    // 奖池播报
    'jackpot.pool': '奖池',
    'jackpot.burned': '总销毁',
    'jackpot.waiting': '等待第一位赢家...',
    
    // 老虎机
    'slot.title': 'BURN SLOTS',
    'slot.subtitle': '5轮符号匹配',
    'slot.return': '100%返还',
    'slot.onchain': '链上模式',
    'slot.pool': '奖池',
    'slot.credits': '凭证',
    'slot.winRate': '胜率',
    'slot.spin': '开始游戏',
    'slot.spinning': '等待结果...',
    'slot.connectWallet': '连接钱包开始',
    'slot.submitted': '游戏已提交',
    'slot.waitingVRF': '等待VRF回调结果...',
    'slot.noWin': '未中奖',
    'slot.tryAgain': '再接再厉！下次好运！',
    'slot.pendingRequest': '检测到挂起旋转请求',
    'slot.waitingVRFCallback': '等待 VRF 回调；如超过 1 小时可尝试解除。',
    'slot.cancel': '解除',
    'slot.unclaimedPrize': '待领取奖金',
    'slot.claim': '领取',
    'slot.claimed': '奖金已领取！',
    'slot.claimFailed': '领取失败',
    'slot.cancelAttempt': '已尝试解除卡住请求',
    'slot.cancelSuccess': '如确实已超时，将会重置你的挂起状态。',
    'slot.cancelFailed': '解除失败',
    'slot.spinFailed': '开始游戏失败',
    'slot.revealing': '开奖中...',
    'slot.waitingRandom': '等待随机数...',
    
    // 投注选择
    'bet.probability': '中奖概率',
    'bet.boost': '提升',
    'bet.perSpin': '凭证/次',
    'bet.credits': '投注凭证',
    'bet.moreCredits': '凭证越多，中奖概率越高',
    
    // 统计
    'stats.totalSpins': '总游戏',
    'stats.totalWins': '总中奖',
    'stats.totalBurned': '总销毁',
    
    // 自动旋转
    'auto.title': '自动旋转',
    'auto.stop': '停止',
    'auto.remaining': '剩余',
    'auto.stopped': '自动旋转已停止',
    'auto.completed': '自动旋转完成',
    'auto.completedDesc': '已完成所有自动旋转',
    'auto.stoppedReason': '由于凭证不足或其他原因',
    
    // 凭证兑换
    'exchange.title': '销毁代币换凭证',
    'exchange.notice': '销毁代币获得游戏凭证（1:1兑换）。凭证永久有效、不可转让，只能用于本钱包玩老虎机。',
    'exchange.tokenBalance': '代币余额',
    'exchange.gameCredits': '游戏凭证',
    'exchange.burn': '销毁',
    'exchange.get': '获得',
    'exchange.token': '代币',
    'exchange.credit': '凭证',
    'exchange.button': '销毁代币换凭证',
    'exchange.burning': '销毁中...',
    'exchange.success': '兑换成功！',
    'exchange.successDesc': '销毁 {amount} 代币，获得 {amount} 游戏凭证',
    'exchange.failed': '兑换失败',
    'exchange.checkAuth': '请检查授权和余额',
    'exchange.insufficientTokens': '代币不足',
    'exchange.needTokens': '需要 {amount} 代币',
    'exchange.burnToPermanent': '销毁代币 → 永久凭证',
    'exchange.exchangeAmount': '兑换数量',
    'exchange.minAmount': '最低10万',
    'exchange.burnIrreversible': '🔥 销毁不可逆',
    'exchange.oneToOne': '🎟️ 1:1 兑换',
    'exchange.nonTransferable': '🔒 凭证不可转账',
    'exchange.winBnb': '💰 中奖领BNB',
    'exchange.pleaseConnectWallet': '请先连接钱包',
    'exchange.insufficientBalance': '余额不足',
    
    // 钱包
    'wallet.title': '钱包中心',
    'wallet.connect': '连接钱包',
    'wallet.connecting': '连接中...',
    'wallet.connected': '已连接',
    'wallet.disconnect': '断开连接',
    'wallet.pleaseConnect': '请先连接钱包',
    'wallet.needConnect': '需要连接钱包才能开始游戏',
    'wallet.insufficientCredits': '凭证不足',
    'wallet.needCredits': '需要 {amount} 游戏凭证。请先销毁代币兑换凭证。',
    'wallet.unclaimedPrize': '🎉 待领取奖励',
    'wallet.claimNow': '立即领取',
    'wallet.claiming': '领取中...',
    'wallet.claimSuccess': '🎉 领取成功！',
    'wallet.claimSuccessDesc': '已将 {amount} BNB 发送至您的钱包',
    'wallet.claimFailed': '领取失败',
    'wallet.claimRetry': '请稍后重试',
    
    // 钱包面板流程
    'exchange.howToPlay': '游戏流程',
    'exchange.step1': '连接BSC钱包',
    'exchange.step2': '焚毁代币兑换游戏凭证',
    'exchange.step3': '使用凭证参与游戏',
    'exchange.step4': '赢取BNB奖池奖励',
    
    // 钱包UI
    'walletUI.selectWallet': '选择钱包',
    'walletUI.detected': '✓ 已检测到',
    'walletUI.notInstalled': '未安装',
    'walletUI.scan': '扫码',
    'walletUI.mobileWallet': '手机钱包扫码连接',
    'walletUI.selectHint': '选择浏览器钱包或扫码连接手机钱包',
    'walletUI.reselectWallet': '重新选择钱包',
    'walletUI.switch': '切换',
    'walletUI.copied': '已复制',
    'walletUI.copiedDesc': '钱包地址已复制到剪贴板',
    'walletUI.bnbBalance': 'BNB 余额',
    'walletUI.tokenBalance': '代币余额',
    'walletUI.gameCredits': '游戏凭证',
    'walletUI.permanent': '永久有效',
    'walletUI.nonTransferable': '不可转让 · 绑定当前钱包',
    
    // 奖励等级
    'reward.title': '奖励与赔付',
    'reward.deflation': '100% 通缩销毁',
    'reward.noFee': '零抽成',
    'reward.tokenBurn': '代币 100% 销毁，中奖奖金分配：',
    'reward.playerGet': '玩家获得（直发钱包）',
    'reward.vrfFee': 'VRF 运营费用',
    'reward.vrfNote': '5%用于 Chainlink VRF 预言机 Gas 费',
    'reward.maxPayout': '单次最大派奖',
    'reward.poolPercent': '奖池的',
    'reward.levels': '奖励等级',
    'reward.betBoost': '投注概率加成',
    'reward.higherBet': '投注越高，稀有符号出现概率越大',
    'reward.symbolOdds': '符号概率 (VRF)',
    'reward.winConditions': '中奖条件',
    'reward.superJackpot': '超级头奖',
    'reward.jackpot': '头奖',
    'reward.first': '一等奖',
    'reward.second': '二等奖',
    'reward.third': '三等奖',
    'reward.small': '小奖',
    'reward.consolation': '安慰奖',
    'reward.middleOnly': '仅中间行有效',
    'reward.payline': '有效赔付',
    'reward.middleRow': '中间行',
    'reward.chainlinkVRF': 'Chainlink VRF 2.5',
    'reward.vrfDesc': '真随机数，5%资金自动充值Gas',
    'reward.moreLevel': '+3个更多奖励等级...',
    
    // 符号稀有度
    'rarity.legendary': '传说',
    'rarity.epic': '史诗',
    'rarity.rare': '稀有',
    'rarity.common': '普通',
    
    // 中奖条件描述
    'condition.superJackpot': '5×7️⃣',
    'condition.jackpot': '5×💎 或 4×7️⃣',
    'condition.first': '5个相同符号',
    'condition.second': '4×稀有符号',
    'condition.third': '4个普通符号',
    'condition.small': '3个相同符号',
    
    // 历史记录页面
    'history.title': '战绩殿堂',
    'history.subtitle': '链上数据 · 公开透明',
    'history.leaderboard': '王者榜单',
    'history.realtime': '实时获胜',
    'history.wins': '次胜利',
    'history.noLeaderboard': '暂无获胜记录',
    'history.beFirst': '成为第一个上榜的王者！',
    'history.recentWins': '最近中奖记录',
    'history.noWins': '暂无获胜记录',
    'history.totalSpins': '全球总对局',
    'history.totalPaidOut': '累计派奖',
    'history.totalPlayers': '获胜玩家数',
    'history.onchain': '🔗',
    'history.justNow': '刚刚',
    'history.minutesAgo': '{n}分钟前',
    'history.hoursAgo': '{n}小时前',
    'history.daysAgo': '{n}天前',
    'history.loadingOnchain': '加载链上数据...',
    'history.retry': '重试',
    'history.maxStreak': '最高 {n} 连胜',
    'history.me': '(我)',
    'history.streak': '{n}连胜',
    'history.myStats': '我的战绩',
    'history.totalGames': '总对局',
    'history.successCashout': '成功收手',
    'history.totalEarned': '累计获得',
    
    // 规则页面
    'rules.pageTitle': '游戏完整指南',
    'rules.pageSubtitle': '三分钟看懂王牌博弈，轻松上手赢取 BNB 奖励',
    'rules.coreTitle': '🎯 游戏核心：猜下一张牌比当前牌「更大」还是「更小」',
    'rules.coreSubtitle': '猜对连胜越多 → 奖励越高 → 最高可赢取整个奖池！',
    'rules.flowTitle': '游戏流程详解',
    'rules.step1Title': '准备凭证',
    'rules.step1What': '什么是凭证？',
    'rules.step1Desc': '凭证是游戏内的虚拟货币，用王牌博弈代币兑换获得。',
    'rules.step1Action': '点击顶部「兑换凭证」按钮，用代币兑换凭证',
    'rules.step1Burn': '兑换后代币会被<strong>永久燃烧</strong>，凭证只能用于游戏',
    'rules.step2Title': '选择门槛等级',
    'rules.step2What': '门槛等级决定你能走多远！',
    'rules.step2Desc': '不同门槛对应不同的最高连胜上限。',
    'rules.step2Credits': '凭证',
    'rules.step2MaxStreak': '最高{n}连胜',
    'rules.step2Tip': '<strong>新手建议：</strong>先从青铜开始熟悉玩法，等熟练后再挑战更高门槛',
    'rules.step3Title': '开始游戏',
    'rules.step3Desc': '系统自动发一张牌，你需要猜下一张牌和当前牌的大小关系：',
    'rules.guessHigher': '猜更大',
    'rules.guessHigherDesc': '你认为下一张牌的点数比当前牌<strong>更大</strong>',
    'rules.guessLower': '猜更小',
    'rules.guessLowerDesc': '你认为下一张牌的点数比当前牌<strong>更小</strong>',
    'rules.guessSame': '猜相同',
    'rules.guessSameDesc': '你认为下一张牌点数<strong>一样大</strong>（高风险高回报）',
    'rules.cardOrder': '🃏 牌面大小：',
    'rules.cardOrderValue': 'A(最小) < 2 < 3 < 4 < 5 < 6 < 7 < 8 < 9 < 10 < J < Q < K(最大)',
    'rules.step4Title': '收手或继续',
    'rules.step4What': '猜对了？',
    'rules.step4Desc': '恭喜！你有两个选择：',
    'rules.cashoutNow': '立即收手',
    'rules.cashoutDesc': '点击「收手」按钮，锁定当前连胜对应的 BNB 奖励，落袋为安！',
    'rules.continueChallenge': '继续挑战',
    'rules.continueDesc': '继续猜下一张，连胜越高奖励越多，但猜错就全没了！',
    'rules.wrongGuess': '<strong>猜错了？</strong> 游戏结束，本局投入的凭证全部损失，不获得任何奖励。记得见好就收！',
    'rules.rewardTitle': '奖励机制详解',
    'rules.rewardFormula': '奖励计算公式',
    'rules.yourReward': '你的奖励',
    'rules.currentPool': '当前奖池',
    'rules.streakPercent': '连胜对应百分比',
    'rules.rewardExample': '例如：奖池 10 BNB，你达成 5 连胜（0.25%），奖励 = 10 × 0.25% = 0.025 BNB',
    'rules.fullRewardTable': '完整连胜奖励表（20级）',
    'rules.entryZone': '🌱 入门区（1-5连胜）',
    'rules.entryNote': '- 青铜玩家可达',
    'rules.advancedZone': '⚡ 进阶区（6-10连胜）',
    'rules.advancedNote': '- 白银玩家可达8连胜',
    'rules.eliteZone': '🔥 精英区（11-15连胜）',
    'rules.eliteNote': '- 黄金玩家可达12连胜',
    'rules.legendZone': '👑 传奇区（16-20连胜）',
    'rules.legendNote': '- 铂金16连胜，钻石清空奖池',
    'rules.streakN': '{n}连胜',
    'rules.aboutBurn': '关于代币燃烧与凭证',
    'rules.burnPoint1': '兑换凭证时，代币会被<strong>永久销毁</strong>',
    'rules.burnPoint2': '燃烧地址：0x000...dead（黑洞地址）',
    'rules.burnPoint3': '<strong>游戏凭证不可转账</strong>，仅限游戏使用（合约层面限制）',
    'rules.burnPoint4': '这是通缩机制，让代币越来越稀缺',
    'rules.aboutPool': '关于 BNB 奖池',
    'rules.poolPoint1': '奖励全部以 <strong>BNB</strong> 发放',
    'rules.poolPoint2': '奖池越大，你能赢的 BNB 越多',
    'rules.poolPoint3': '领取奖励时会扣除 5% 用于 <strong>Chainlink VRF 预言机服务费</strong>（非项目方收取）',
    'rules.strategyTitle': '策略建议',
    'rules.recommended': '✅ 推荐做法',
    'rules.recommend1': '当前牌是 2 或 3 → 大胆猜「更大」（胜率高）',
    'rules.recommend2': '当前牌是 Q 或 K → 果断猜「更小」（胜率高）',
    'rules.recommend3': '连胜 3 次以上 → 考虑收手，小赚即安',
    'rules.recommend4': '奖池很大时 → 适合冲高连胜',
    'rules.avoid': '❌ 避免做法',
    'rules.avoid1': '当前牌是 7 时 → 无论猜大猜小胜率都是 50%',
    'rules.avoid2': '贪心不收手 → 高连胜很难维持',
    'rules.avoid3': '盲目选高门槛 → 新手容易亏损',
    'rules.avoid4': '频繁猜「相同」 → 胜率只有约 6%',
    'rules.oddsReference': '📊 各点数胜率参考',
    'rules.guessLarger': '猜大',
    'rules.guessSmaller': '猜小',
    'rules.riskZone': '约 50% 风险区',
    'rules.fairnessTitle': '公平性保障',
    'rules.chainlinkVRF': 'Chainlink VRF',
    'rules.chainlinkDesc': '使用业界最权威的去中心化随机数服务，牌面完全随机，无法预测或操控',
    'rules.onchainTransparent': '链上透明',
    'rules.onchainDesc': '所有游戏记录、奖励发放都在 BSC 链上公开可查，任何人都可以验证',
    'rules.smartContract': '智能合约',
    'rules.contractDesc': '游戏逻辑由智能合约自动执行，代码开源，无人工干预',
    'rules.faqTitle': '常见问题',
    'rules.faq1Q': 'Q: 门槛等级有什么区别？',
    'rules.faq1A': '门槛等级决定了你最高能达到的连胜数。比如青铜门槛最高只能到 5 连胜，而钻石门槛可以挑战 20 连胜清空奖池。门槛越高，需要燃烧的凭证越多，但潜在奖励也越大。',
    'rules.faq2Q': 'Q: 猜「相同」有什么特别？',
    'rules.faq2A': '猜「相同」的胜率只有约 6%（51 张牌中有 3 张相同点数），风险很高。但如果猜对，会获得<strong>额外 +2 连胜加成</strong>，直接跳 2 级奖励！适合在关键时刻博一把。',
    'rules.faq3Q': 'Q: 奖励怎么领取？',
    'rules.faq3A': '收手成功后，奖励会<strong>自动转入你的钱包</strong>（显示为"内部交易"，不会出现在普通交易列表中，但余额会立即增加）。领取时已扣除 5% 用于 Chainlink VRF 预言机服务费（保障随机数服务持续运行，非项目方收取）。只有在极少数自动转账失败的情况下，才需要点击「待领取」按钮手动提取。',
    'rules.faq4Q': 'Q: 为什么要等待 VRF？',
    'rules.faq4A': '每次猜测后，需要等待 Chainlink VRF 返回随机数来决定下一张牌。这个过程通常需要 5-15 秒。这是确保公平性的必要环节，随机数由去中心化网络生成，无法被任何人操控。',
    'rules.faq5Q': 'Q: 凭证可以退回吗？',
    'rules.faq5A': '不可以。兑换凭证时代币会被永久燃烧，凭证只能用于游戏。游戏开始后，无论输赢，本局投入的凭证都会被消耗。请根据自己的承受能力合理游戏。',
    'rules.faq6Q': 'Q: 为什么游戏中途被自动收手了？',
    'rules.faq6A': '这是<strong>奖池保护机制</strong>。当多人同时游戏时，系统需要为每位玩家锁定对应连胜级别的潜在奖励。如果奖池可用余额不足以锁定下一级奖励，系统会自动结算您<strong>当前的收益</strong>，确保您不会因后续奖池耗尽而血本无归。这是保护性措施，不是惩罚。出现这种情况时，您仍然可以获得当前连胜对应的奖励。',
    
    // HiLo游戏
    'hilo.gameContract': '游戏合约',
    'hilo.tokenContract': '代币合约',
    'hilo.fundsAllocation': '💰 资金分配：',
    'hilo.playerReward': '95% 用于玩家奖励发放',
    'hilo.vrfFunding': '5% 用于 VRF 随机数服务充值',
    'hilo.unclaimedBnb': '您有 {amount} BNB 待领取',
    'hilo.claimReward': '领取奖励',
    'hilo.currentPool': '当前奖池',
    'hilo.totalBurned': '全网燃烧',
    'hilo.myCredits': '我的凭证',
    'hilo.currentCard': '当前牌',
    'hilo.nextCard': '下一张',
    'hilo.streak': '连胜',
    'hilo.selectTier': '选择门槛等级',
    'hilo.maxPool': '最高 {n}% 奖池',
    'hilo.needMore': '还差 {n}',
    'hilo.authorizing': '正在授权...',
    'hilo.clickConnect': '点击连接钱包',
    'hilo.startGame': '开始游戏',
    'hilo.higher': '更高',
    'hilo.lower': '更低',
    'hilo.same': '相同',
    'hilo.sameBonus': '+2级',
    'hilo.cashout': '收手兑现 {percent}% 奖池 (≈{amount} BNB)',
    'hilo.settling': '正在结算，请稍候...',
    'hilo.revealing': '揭示中...',
    'hilo.correct': '正确!',
    'hilo.wrong': '错误!',
    'hilo.congrats': '🎉 恭喜获得 {percent}% 奖池!',
    'hilo.gameOver': '游戏结束 - 连胜 {n} 次',
    'hilo.pendingReward': '待领取奖励',
    'hilo.claimNow': '立即领取奖励',
    'hilo.gasFeeNote': '领取时需支付少量Gas费，95%奖励到账',
    'hilo.playAgain': '再来一局',
    'hilo.cashoutSuccess': '🎉 收手成功！',
    'hilo.cashoutSuccessDesc': '{amount} BNB 已自动转入钱包',
    'hilo.claimSuccess': '🎉 领取成功!',
    'hilo.claimSuccessDesc': '{amount} BNB 已发送到您的钱包',
    'hilo.rewardClaimed': '奖励已领取!',
    // 奖池透明度
    'hilo.availablePool': '可用余额',
    'hilo.lockedPool': '已锁定',
    'hilo.safeStreak': '安全连胜',
    'hilo.poolWarningTitle': '⚠️ 奖池余额较低',
    'hilo.poolWarningDesc': '当前可用余额 {available} BNB，安全连胜仅 {safe} 级。建议选择更低门槛或稍后再试。',
    'hilo.poolWarningConfirm': '我已了解，继续游戏',
    'hilo.poolWarningCancel': '暂不开始',
    'hilo.poolStatusGood': '✅ 奖池充足',
    'hilo.poolStatusWarning': '⚠️ 注意锁定',
    'hilo.poolStatusDanger': '🚨 余额紧张',
    
    // HiLoResults组件
    'hiloResults.consumed': '消耗',
    'hiloResults.won': '赢得',
    'hiloResults.gameHistory': '游戏记录',
    'hiloResults.noHistory': '暂无游戏记录',
    'hiloResults.cashedOut': '收手 x{n}',
    'hiloResults.guessedWrong': '猜错 x{n}',
    'hiloResults.credits': '凭证',
    
    // FAQ扩展
    'faq.title': '❓ 常见问题',
    'faq.q1': '我的代币去哪了？',
    'faq.a1': '代币被销毁到黑洞地址，永久减少流通供应，不是被任何人拿走了',
    'faq.q2': '中奖后钱多久到账？',
    'faq.a2': 'VRF 回调确认后约 2-3 个区块（约 10 秒）自动到账',
    'faq.q3': '为什么显示"等待VRF回调"？',
    'faq.a3': 'Chainlink VRF 需要 2-3 个区块确认随机数，请耐心等待。如超过 1 小时未返回，可尝试解除卡住请求',
    'faq.q4': '凭证可以退回代币吗？',
    'faq.a4': '不可以。凭证只能用于游戏，代币已被销毁，这是不可逆的',
    'faq.poolSource': '💰 奖池的钱从哪来？',
    'faq.poolSourceAnswer1': '奖池资金来源于交易税的 3%！',
    'faq.poolSourceAnswer2': '每一笔代币交易（买入/卖出）都会产生交易税，其中 3% 会自动进入游戏奖池，用于奖励中奖玩家。',
    'faq.poolSourceNote': '工作原理：交易税 → 自动兑换为 BNB → 注入奖池合约',
    'faq.poolSourceTip': '交易越活跃，奖池越大，中奖奖励越多！',
    'faq.whyCredits': '为什么要用凭证而不是直接用代币？',
    'faq.whyCreditsAnswer': '凭证系统可以减少链上交易次数，节省 Gas 费。你可以一次兑换大量凭证，然后多次游戏，体验更流畅。',
    'faq.higherBet': '投注越高真的概率越大吗？',
    'faq.higherBetAnswer': '是的！高投注会增加稀有符号（如7️⃣💎）的出现概率。500K投注相比20K有20倍的概率加成，但请量力而行。',
    
    // 赔付表
    'payoutTable.title': '完整赔付表',
    
    // 页脚
    'footer.onchain': '链上版本 | 智能合约已连接',
    'footer.poweredBy': 'Powered by BNB Chain & Chainlink VRF',
    
    // 中奖弹窗
    'win.prize': '获得奖金',
    'win.clickToClose': '点击任意位置关闭',
    
    // 中奖显示 (WinDisplay)
    'winDisplay.first': '👑 一等奖 👑',
    'winDisplay.second': '🔔 二等奖 🔔',
    'winDisplay.third': '⭐ 三等奖 ⭐',
    'winDisplay.small': '🍀 小奖 🍀',
    'winDisplay.consolation': '🎁 安慰奖 🎁',
    'winDisplay.paylines': '{n} 条赔付线中奖',
    'winDisplay.poolPercent': '奖池 {n}%',
    'winDisplay.more': '更多',
    
    // 紧凑历史记录 (CompactGameHistory)
    'compactHistory.title': '最近中奖',
    'compactHistory.live': '实时',
    'compactHistory.noRecords': '暂无中奖记录',
    'compactHistory.viewMore': '查看更多 →',
    
    // 404页面
    'notFound.title': '404',
    'notFound.message': '页面未找到',
    'notFound.backHome': '返回首页',
    
    // 钱包提示
    'howToPlay.binanceWallet': '币安钱包',
    
    // 音频控制
    'audio.mute': '静音',
    'audio.unmute': '取消静音',
    'audio.bgMusicOn': '开启背景音乐',
    'audio.bgMusicOff': '关闭背景音乐',
    
    // 自动旋转
    'autoSpin.title': '自动旋转',
    'autoSpin.remaining': '自动',
    'autoSpin.stop': '停止',
    'autoSpin.selectCount': '选择自动旋转次数',
    'autoSpin.times': '次',
    'autoSpin.start': '开始自动',
    'autoSpin.hint': '中途可随时点击停止',
    
    // 赔付表组件
    'rewardTiers.title': '奖励与赔付表',
    'rewardTiers.deflationTitle': '🎯 100% 通缩销毁 | 零抽成',
    'rewardTiers.deflationHighlight': '✨ 代币 100% 销毁到黑洞地址',
    'rewardTiers.deflationPoint1': '中奖奖金：95% 玩家获得，5% VRF 运营费',
    'rewardTiers.deflationPoint2': '无隐藏费用，无平台抽成',
    'rewardTiers.deflationPoint3': '智能合约透明可验证',
    'rewardTiers.poolProtection': '奖池保护机制',
    'rewardTiers.maxPayout': '单次最大派奖: 奖池的',
    'rewardTiers.zeroReserve': '奖池资金 100% 用于派奖，零储备金',
    'rewardTiers.levels': '奖励等级 (基于奖池)',
    'rewardTiers.payoutNote': '实际派奖 = 奖池 × 百分比 (不超过最大派奖限制)',
    'rewardTiers.betBonus': '投注概率加成',
    'rewardTiers.winOdds': '中奖概率',
    'rewardTiers.betTip': '投注越高，稀有符号出现概率越大',
    'rewardTiers.symbolRarity': '符号稀有度',
    'rewardTiers.winConditions': '中奖条件 (5符号匹配)',
    'rewardTiers.winConditionsNote': '中奖根据5个符号中相同符号的数量判定（慷慨版：约60%中奖率）',
    'rewardTiers.condition.superJackpot': '5个全是 7️⃣',
    'rewardTiers.condition.jackpot': '5个全是 💎，或4个 7️⃣',
    'rewardTiers.condition.first': '任意5个相同符号',
    'rewardTiers.condition.second': '4个相同的稀有符号 (7️⃣💎👑🔔⭐)',
    'rewardTiers.condition.third': '4个相同的普通符号 (🍒🍋🍊🍇🍀)',
    'rewardTiers.condition.small': '任意3个相同符号',
    'rewardTiers.condition.consolation': '任意2个相同符号 (~45%概率)',
    'rewardTiers.displayNote': '结果显示说明',
    'rewardTiers.displayDesc1': '老虎机显示3行符号，但只有中间行（高亮行）是实际开奖结果。',
    'rewardTiers.displayDesc2': '上下两行为装饰符号，不参与中奖判定。',
    'rewardTiers.vrfDesc': '使用 Chainlink VRF 生成真随机数，确保结果公平不可预测。每次转动消耗 VRF 请求，约 2-3 区块后返回结果。',
  },
  en: {
    // Navigation
    'nav.game': 'Game',
    'nav.history': 'Hall of Fame',
    'nav.rules': 'Guide',
    
    // Navbar
    'navbar.brandName': 'ACE HILO',
    'navbar.tagline': 'GAMEFI · Burn Deflation Protocol',
    'navbar.unclaimed': 'Unclaimed',
    'navbar.unclaimedReward': 'Unclaimed Reward',
    'navbar.claim': 'Claim',
    'navbar.claimNow': 'Claim Now',
    'navbar.claimSuccess': 'Successfully claimed {amount} BNB!',
    'navbar.claimFailed': 'Claim failed, please try again',
    
    // VRF Waiting
    'vrf.waiting': 'Waiting for on-chain confirmation',
    'vrf.timeout': 'Waiting timeout',
    'vrf.generating': 'Chainlink VRF is generating verifiable random number',
    'vrf.maybeStuck': 'VRF callback may be stuck, try canceling the request',
    'vrf.usually': 'Usually takes 10-30 seconds',
    'vrf.cancel': 'Cancel Request',
    'vrf.doNotClose': 'Do not close the page, result will update automatically',
    'vrf.formatMin': '{min}m {sec}s',
    'vrf.formatSec': '{sec}s',
    
    // Success Animation
    'success.arrived': 'Received!',
    'success.afterFee': '(after 5% fee)',
    'success.autoTransfer': '💡 Reward auto-transferred via internal transaction',
    
    // Reward Ladder
    'ladder.title': 'Reward Ladder',
    'ladder.currentLevel': 'Current Level',
    'ladder.maxStreak': 'Max {n} streak',
    'ladder.maxWin': 'Max Win',
    'ladder.pool': 'Pool',
    'ladder.nonCumulative': '(Non-cumulative, replacement)',
    'ladder.nStreak': '{n} streak',
    'ladder.needHigher': 'Need higher tier',
    'ladder.currentCashout': 'Current cashout',
    'ladder.level': 'Level',
    
    // Horizontal Reward
    'hreward.title': 'Reward Ladder',
    'hreward.currentLevel': 'Current Level:',
    'hreward.maxStreakLabel': '(Max {n} streak)',
    'hreward.currentStreak': 'Current Streak',
    'hreward.streakCount': 'Streak Count',
    'hreward.currentReward': 'Current Reward',
    'hreward.nextTarget': 'Next Target',
    'hreward.winMore': 'Win 1 more → {n} streak',
    'hreward.reachedMax': '🎉 Max reached',
    'hreward.upgradeUnlock': 'Upgrade tier to unlock more',
    'hreward.entryZone': 'Entry Zone',
    'hreward.advancedZone': 'Advanced Zone',
    'hreward.eliteZone': 'Elite Zone',
    'hreward.legendZone': 'Legend Zone',
    'hreward.streakRange1': '1-5 streak',
    'hreward.streakRange2': '6-10 streak',
    'hreward.streakRange3': '11-15 streak',
    'hreward.streakRange4': '16-20 streak',
    'hreward.yourMaxTarget': 'Your max target ({tier} tier):',
    'hreward.nStreakEquals': '{n} streak = {percent}%',
    'hreward.percentDetail': '📊 Reward percentage details (% of current pool)',
    'hreward.exampleNote': '💡 Example: If pool is 1 BNB and you cash out at 5 streak, you get 0.25% × 1 BNB = 0.0025 BNB (0.002375 BNB after 5% fee)',
    'hreward.ruleNote': '💡 <strong>Rule</strong>: Each correct guess +1 streak, rewards increase with streak (non-cumulative)',
    'hreward.cashoutTip': '🎯 Cash out anytime · Wrong guess loses all accumulated progress',
    
    // Home tags
    'home.tag.symbols': '5-Symbol Match',
    'home.tag.payline': 'Middle Row Pays',
    'home.tag.symbolCount': '10 Symbols',
    'home.tag.return': '100% Return',
    
    // Contract addresses
    'contract.game': 'Game Contract',
    'contract.token': 'Token Contract',
    'contract.copy': 'Copy Address',
    'contract.view': 'View on BSCScan',
    'contract.copied': 'Address Copied',
    'contract.pending': 'Pending...',
    'contract.gameContractCopied': 'Game contract address copied!',
    'contract.tokenContractCopied': 'Token contract address copied!',
    
    // Jackpot ticker
    'jackpot.pool': 'Prize Pool',
    'jackpot.burned': 'Total Burned',
    'jackpot.waiting': 'Waiting for first winner...',
    
    // Slot machine
    'slot.title': 'BURN SLOTS',
    'slot.subtitle': '5-Reel Symbol Match',
    'slot.return': '100% Return',
    'slot.onchain': 'On-Chain',
    'slot.pool': 'Pool',
    'slot.credits': 'Credits',
    'slot.winRate': 'Win Rate',
    'slot.spin': 'SPIN',
    'slot.spinning': 'Waiting...',
    'slot.connectWallet': 'Connect to Play',
    'slot.submitted': '🎰 Game Submitted',
    'slot.waitingVRF': 'Waiting for VRF callback...',
    'slot.noWin': 'No Win',
    'slot.tryAgain': 'Better luck next time!',
    'slot.pendingRequest': 'Pending spin request detected',
    'slot.waitingVRFCallback': 'Waiting for VRF callback; try to cancel if stuck for over 1 hour.',
    'slot.cancel': 'Cancel',
    'slot.unclaimedPrize': 'Unclaimed Prize',
    'slot.claim': 'Claim',
    'slot.claimed': 'Prize Claimed!',
    'slot.claimFailed': 'Claim Failed',
    'slot.cancelAttempt': 'Attempting to cancel stuck request',
    'slot.cancelSuccess': 'If timed out, your pending status will be reset.',
    'slot.cancelFailed': 'Cancel Failed',
    'slot.spinFailed': 'Spin Failed',
    'slot.revealing': 'Revealing...',
    'slot.waitingRandom': 'Waiting for randomness...',
    
    // Bet selector
    'bet.probability': 'Win Probability',
    'bet.boost': 'Boost',
    'bet.perSpin': 'Credits/Spin',
    'bet.credits': 'Bet Credits',
    'bet.moreCredits': 'More credits = higher odds',
    
    // Stats
    'stats.totalSpins': 'Total Spins',
    'stats.totalWins': 'Total Wins',
    'stats.totalBurned': 'Total Burned',
    
    // Auto spin
    'auto.title': 'Auto Spin',
    'auto.stop': 'Stop',
    'auto.remaining': 'Left',
    'auto.stopped': 'Auto Spin Stopped',
    'auto.completed': 'Auto Spin Complete',
    'auto.completedDesc': 'All auto spins completed',
    'auto.stoppedReason': 'Due to insufficient credits or other reasons',
    
    // Credits exchange
    'exchange.title': 'Burn Tokens for Credits',
    'exchange.notice': 'Burn tokens to get game credits (1:1 exchange). Credits are permanent, non-transferable, and can only be used in this wallet.',
    'exchange.tokenBalance': 'Token Balance',
    'exchange.gameCredits': 'Game Credits',
    'exchange.burn': 'Burn',
    'exchange.get': 'Get',
    'exchange.token': 'Tokens',
    'exchange.credit': 'Credits',
    'exchange.button': 'Burn Tokens for Credits',
    'exchange.burning': 'Burning...',
    'exchange.success': 'Exchange Success!',
    'exchange.successDesc': 'Burned {amount} tokens, got {amount} credits',
    'exchange.failed': 'Exchange Failed',
    'exchange.checkAuth': 'Please check authorization and balance',
    'exchange.insufficientTokens': 'Insufficient Tokens',
    'exchange.needTokens': 'Need {amount} tokens',
    'exchange.burnToPermanent': 'Burn Tokens → Permanent Credits',
    'exchange.exchangeAmount': 'Exchange Amount',
    'exchange.minAmount': 'Min 100K',
    'exchange.burnIrreversible': '🔥 Burn is irreversible',
    'exchange.oneToOne': '🎟️ 1:1 Exchange',
    'exchange.nonTransferable': '🔒 Credits non-transferable',
    'exchange.winBnb': '💰 Win BNB',
    'exchange.pleaseConnectWallet': 'Please connect wallet',
    'exchange.insufficientBalance': 'Insufficient balance',
    
    // Wallet
    'wallet.title': 'Wallet Center',
    'wallet.connect': 'Connect Wallet',
    'wallet.connecting': 'Connecting...',
    'wallet.connected': 'Connected',
    'wallet.disconnect': 'Disconnect',
    'wallet.pleaseConnect': 'Please Connect Wallet',
    'wallet.needConnect': 'Connect wallet to start playing',
    'wallet.insufficientCredits': 'Insufficient Credits',
    'wallet.needCredits': 'Need {amount} credits. Please burn tokens first.',
    'wallet.unclaimedPrize': '🎉 Unclaimed Reward',
    'wallet.claimNow': 'Claim Now',
    'wallet.claiming': 'Claiming...',
    'wallet.claimSuccess': '🎉 Claim Success!',
    'wallet.claimSuccessDesc': 'Sent {amount} BNB to your wallet',
    'wallet.claimFailed': 'Claim Failed',
    'wallet.claimRetry': 'Please try again later',
    
    // Wallet Panel Flow
    'exchange.howToPlay': 'How to Play',
    'exchange.step1': 'Connect BSC Wallet',
    'exchange.step2': 'Burn tokens for game credits',
    'exchange.step3': 'Use credits to play games',
    'exchange.step4': 'Win BNB from prize pool',
    
    // Wallet UI
    'walletUI.selectWallet': 'Select Wallet',
    'walletUI.detected': '✓ Detected',
    'walletUI.notInstalled': 'Not Installed',
    'walletUI.scan': 'Scan',
    'walletUI.mobileWallet': 'Scan to connect mobile wallet',
    'walletUI.selectHint': 'Choose browser wallet or scan for mobile',
    'walletUI.reselectWallet': 'Reselect Wallet',
    'walletUI.switch': 'Switch',
    'walletUI.copied': 'Copied',
    'walletUI.copiedDesc': 'Wallet address copied to clipboard',
    'walletUI.bnbBalance': 'BNB Balance',
    'walletUI.tokenBalance': 'Token Balance',
    'walletUI.gameCredits': 'Game Credits',
    'walletUI.permanent': 'Permanent',
    'walletUI.nonTransferable': 'Non-transferable · Bound to wallet',
    
    // Reward tiers
    'reward.title': 'Rewards & Payouts',
    'reward.deflation': '100% Deflationary Burn',
    'reward.noFee': 'Zero Fees',
    'reward.tokenBurn': 'Tokens 100% burned, prize distribution:',
    'reward.playerGet': 'Player Gets (Direct to Wallet)',
    'reward.vrfFee': 'VRF Operation Fee',
    'reward.vrfNote': '5% for Chainlink VRF Oracle Gas',
    'reward.maxPayout': 'Max Single Payout',
    'reward.poolPercent': 'of Pool',
    'reward.levels': 'Prize Levels',
    'reward.betBoost': 'Bet Probability Boost',
    'reward.higherBet': 'Higher bet = higher rare symbol chance',
    'reward.symbolOdds': 'Symbol Odds (VRF)',
    'reward.winConditions': 'Win Conditions',
    'reward.superJackpot': 'Super Jackpot',
    'reward.jackpot': 'Jackpot',
    'reward.first': '1st Prize',
    'reward.second': '2nd Prize',
    'reward.third': '3rd Prize',
    'reward.small': 'Small Win',
    'reward.consolation': 'Consolation',
    'reward.middleOnly': 'Middle row only',
    'reward.payline': 'Valid Payline',
    'reward.middleRow': 'Middle Row',
    'reward.chainlinkVRF': 'Chainlink VRF 2.5',
    'reward.vrfDesc': 'True randomness, 5% auto-funds Gas',
    'reward.moreLevel': '+3 more prize levels...',
    
    // Symbol rarity
    'rarity.legendary': 'Legendary',
    'rarity.epic': 'Epic',
    'rarity.rare': 'Rare',
    'rarity.common': 'Common',
    
    // Win conditions
    'condition.superJackpot': '5×7️⃣',
    'condition.jackpot': '5×💎 or 4×7️⃣',
    'condition.first': '5 of a kind',
    'condition.second': '4× Rare',
    'condition.third': '4× Common',
    'condition.small': '3 of a kind',
    
    // History page
    'history.title': 'Hall of Fame',
    'history.subtitle': 'On-chain Data · Transparent',
    'history.leaderboard': 'Leaderboard',
    'history.realtime': 'Live Wins',
    'history.wins': 'wins',
    'history.noLeaderboard': 'No winning records yet',
    'history.beFirst': 'Be the first champion!',
    'history.recentWins': 'Recent Wins',
    'history.noWins': 'No wins yet',
    'history.totalSpins': 'Global Rounds',
    'history.totalPaidOut': 'Total Paid Out',
    'history.totalPlayers': 'Winning Players',
    'history.onchain': '🔗',
    'history.justNow': 'Just now',
    'history.minutesAgo': '{n}m ago',
    'history.hoursAgo': '{n}h ago',
    'history.daysAgo': '{n}d ago',
    'history.loadingOnchain': 'Loading on-chain data...',
    'history.retry': 'Retry',
    'history.maxStreak': 'Max {n} streak',
    'history.me': '(Me)',
    'history.streak': '{n} streak',
    'history.myStats': 'My Stats',
    'history.totalGames': 'Total Games',
    'history.successCashout': 'Success Cashouts',
    'history.totalEarned': 'Total Earned',
    
    // Rules page
    'rules.pageTitle': 'Complete Game Guide',
    'rules.pageSubtitle': 'Learn Ace Hi-Lo in 3 minutes and start winning BNB rewards',
    'rules.coreTitle': '🎯 Core: Guess if the next card is higher or lower than the current card',
    'rules.coreSubtitle': 'More consecutive wins → Higher rewards → Win the entire prize pool!',
    'rules.flowTitle': 'Game Flow Explained',
    'rules.step1Title': 'Get Credits',
    'rules.step1What': 'What are credits?',
    'rules.step1Desc': 'Credits are in-game currency obtained by exchanging Ace tokens.',
    'rules.step1Action': 'Click the "Exchange Credits" button at the top',
    'rules.step1Burn': 'Tokens are <strong>permanently burned</strong> after exchange, credits can only be used for gaming',
    'rules.step2Title': 'Choose Tier Level',
    'rules.step2What': 'Tier level determines how far you can go!',
    'rules.step2Desc': 'Different tiers have different max streak limits.',
    'rules.step2Credits': 'Credits',
    'rules.step2MaxStreak': 'Max {n} streak',
    'rules.step2Tip': '<strong>Beginners:</strong> Start with Bronze to learn, then try higher tiers',
    'rules.step3Title': 'Start Playing',
    'rules.step3Desc': 'System deals a card, guess the relationship with the next card:',
    'rules.guessHigher': 'Guess Higher',
    'rules.guessHigherDesc': 'You think the next card is <strong>higher</strong> than current',
    'rules.guessLower': 'Guess Lower',
    'rules.guessLowerDesc': 'You think the next card is <strong>lower</strong> than current',
    'rules.guessSame': 'Guess Same',
    'rules.guessSameDesc': 'You think the next card has <strong>same value</strong> (high risk, high reward)',
    'rules.cardOrder': '🃏 Card Order:',
    'rules.cardOrderValue': 'A(lowest) < 2 < 3 < 4 < 5 < 6 < 7 < 8 < 9 < 10 < J < Q < K(highest)',
    'rules.step4Title': 'Cash Out or Continue',
    'rules.step4What': 'Guessed right?',
    'rules.step4Desc': 'Congrats! You have two choices:',
    'rules.cashoutNow': 'Cash Out Now',
    'rules.cashoutDesc': 'Click "Cash Out" to lock in your BNB reward!',
    'rules.continueChallenge': 'Continue Challenge',
    'rules.continueDesc': 'Keep going for higher rewards, but lose everything if wrong!',
    'rules.wrongGuess': '<strong>Guessed wrong?</strong> Game over, all credits lost, no reward. Know when to stop!',
    'rules.rewardTitle': 'Reward Mechanism Explained',
    'rules.rewardFormula': 'Reward Formula',
    'rules.yourReward': 'Your Reward',
    'rules.currentPool': 'Current Pool',
    'rules.streakPercent': 'Streak Percentage',
    'rules.rewardExample': 'Example: Pool 10 BNB, 5 streak (0.25%), Reward = 10 × 0.25% = 0.025 BNB',
    'rules.fullRewardTable': 'Complete Streak Reward Table (20 Levels)',
    'rules.entryZone': '🌱 Entry Zone (1-5 streak)',
    'rules.entryNote': '- Bronze tier can reach',
    'rules.advancedZone': '⚡ Advanced Zone (6-10 streak)',
    'rules.advancedNote': '- Silver tier can reach 8 streak',
    'rules.eliteZone': '🔥 Elite Zone (11-15 streak)',
    'rules.eliteNote': '- Gold tier can reach 12 streak',
    'rules.legendZone': '👑 Legend Zone (16-20 streak)',
    'rules.legendNote': '- Platinum 16 streak, Diamond clears pool',
    'rules.streakN': '{n} streak',
    'rules.aboutBurn': 'About Token Burn & Credits',
    'rules.burnPoint1': 'Tokens are <strong>permanently destroyed</strong> when exchanging',
    'rules.burnPoint2': 'Burn address: 0x000...dead (Dead address)',
    'rules.burnPoint3': '<strong>Credits are non-transferable</strong>, gaming only (contract enforced)',
    'rules.burnPoint4': 'This is deflation, making tokens increasingly scarce',
    'rules.aboutPool': 'About BNB Prize Pool',
    'rules.poolPoint1': 'All rewards paid in <strong>BNB</strong>',
    'rules.poolPoint2': 'Bigger pool = more BNB you can win',
    'rules.poolPoint3': '5% deducted for <strong>Chainlink VRF oracle fee</strong> (not taken by project)',
    'rules.strategyTitle': 'Strategy Tips',
    'rules.recommended': '✅ Recommended',
    'rules.recommend1': 'Current card is 2 or 3 → Confidently guess "Higher" (high win rate)',
    'rules.recommend2': 'Current card is Q or K → Guess "Lower" decisively (high win rate)',
    'rules.recommend3': '3+ streak → Consider cashing out, secure profits',
    'rules.recommend4': 'Big pool → Go for higher streaks',
    'rules.avoid': '❌ Avoid',
    'rules.avoid1': 'Current card is 7 → 50% win rate either way',
    'rules.avoid2': 'Being greedy → High streaks are hard to maintain',
    'rules.avoid3': 'Blindly choosing high tiers → Beginners lose easily',
    'rules.avoid4': 'Frequent "Same" guesses → Only ~6% win rate',
    'rules.oddsReference': '📊 Win Rate Reference by Card',
    'rules.guessLarger': 'Guess Higher',
    'rules.guessSmaller': 'Guess Lower',
    'rules.riskZone': '~50% Risk Zone',
    'rules.fairnessTitle': 'Fairness Guarantee',
    'rules.chainlinkVRF': 'Chainlink VRF',
    'rules.chainlinkDesc': 'Industry-leading decentralized randomness, cards are completely random and unpredictable',
    'rules.onchainTransparent': 'On-chain Transparent',
    'rules.onchainDesc': 'All game records and payouts are public on BSC, anyone can verify',
    'rules.smartContract': 'Smart Contract',
    'rules.contractDesc': 'Game logic auto-executed by smart contract, open source, no human intervention',
    'rules.faqTitle': 'FAQ',
    'rules.faq1Q': 'Q: What\'s the difference between tier levels?',
    'rules.faq1A': 'Tier level determines your max streak. Bronze caps at 5 streak, while Diamond can reach 20 streak and clear the pool. Higher tiers require more credits but offer bigger potential rewards.',
    'rules.faq2Q': 'Q: What\'s special about guessing "Same"?',
    'rules.faq2A': 'Guessing "Same" has only ~6% win rate (3 cards with same value out of 51), very risky. But if correct, you get <strong>+2 streak bonus</strong>, jumping 2 reward levels! Great for clutch moments.',
    'rules.faq3Q': 'Q: How do I receive rewards?',
    'rules.faq3A': 'After cashing out, rewards are <strong>automatically transferred to your wallet</strong> (shown as "Internal Transaction", won\'t appear in normal transaction list but balance updates immediately). 5% is already deducted for Chainlink VRF oracle fee (not project revenue). Manual claiming is only needed if automatic transfer fails.',
    'rules.faq4Q': 'Q: Why wait for VRF?',
    'rules.faq4A': 'After each guess, Chainlink VRF returns a random number for the next card. Usually takes 5-15 seconds. This ensures fairness - randomness generated by decentralized network, impossible to manipulate.',
    'rules.faq5Q': 'Q: Can I get credits back?',
    'rules.faq5A': 'No. Tokens are permanently burned when exchanging, credits can only be used for gaming. Once a game starts, credits are consumed regardless of outcome. Please play responsibly.',
    'rules.faq6Q': 'Q: Why was my game auto-settled mid-game?',
    'rules.faq6A': 'This is the <strong>Pool Protection Mechanism</strong>. When multiple players are gaming simultaneously, the system needs to lock potential rewards for each player. If the available pool balance is insufficient to lock the next level\'s reward, the system auto-settles your <strong>current winnings</strong>, ensuring you don\'t lose everything if the pool runs dry later. This is protective, not punitive. You still receive rewards for your current streak.',
    
    // HiLo Game
    'hilo.gameContract': 'Game Contract',
    'hilo.tokenContract': 'Token Contract',
    'hilo.fundsAllocation': '💰 Funds Allocation:',
    'hilo.playerReward': '95% for player rewards',
    'hilo.vrfFunding': '5% for VRF randomness service',
    'hilo.unclaimedBnb': 'You have {amount} BNB to claim',
    'hilo.claimReward': 'Claim Reward',
    'hilo.currentPool': 'Current Pool',
    'hilo.totalBurned': 'Total Burned',
    'hilo.myCredits': 'My Credits',
    'hilo.currentCard': 'Current Card',
    'hilo.nextCard': 'Next Card',
    'hilo.streak': 'Streak',
    'hilo.selectTier': 'Select Tier Level',
    'hilo.maxPool': 'Max {n}% Pool',
    'hilo.needMore': 'Need {n} more',
    'hilo.authorizing': 'Authorizing...',
    'hilo.clickConnect': 'Click to Connect Wallet',
    'hilo.startGame': 'Start Game',
    'hilo.higher': 'Higher',
    'hilo.lower': 'Lower',
    'hilo.same': 'Same',
    'hilo.sameBonus': '+2 Level',
    'hilo.cashout': 'Cash Out {percent}% Pool (≈{amount} BNB)',
    'hilo.settling': 'Settling, please wait...',
    'hilo.revealing': 'Revealing...',
    'hilo.correct': 'Correct!',
    'hilo.wrong': 'Wrong!',
    'hilo.congrats': '🎉 Won {percent}% of Pool!',
    'hilo.gameOver': 'Game Over - {n} Streak',
    'hilo.pendingReward': 'Pending Reward',
    'hilo.claimNow': 'Claim Reward Now',
    'hilo.gasFeeNote': 'Small gas fee required, 95% reward received',
    'hilo.playAgain': 'Play Again',
    'hilo.cashoutSuccess': '🎉 Cash Out Success!',
    'hilo.cashoutSuccessDesc': '{amount} BNB sent to your wallet',
    'hilo.claimSuccess': '🎉 Claim Success!',
    'hilo.claimSuccessDesc': '{amount} BNB sent to your wallet',
    'hilo.rewardClaimed': 'Reward Claimed!',
    // Pool Transparency
    'hilo.availablePool': 'Available',
    'hilo.lockedPool': 'Locked',
    'hilo.safeStreak': 'Safe Streak',
    'hilo.poolWarningTitle': '⚠️ Low Pool Balance',
    'hilo.poolWarningDesc': 'Available balance is {available} BNB, safe streak only {safe} levels. Consider lower tier or wait.',
    'hilo.poolWarningConfirm': 'I understand, continue',
    'hilo.poolWarningCancel': 'Not now',
    'hilo.poolStatusGood': '✅ Pool Sufficient',
    'hilo.poolStatusWarning': '⚠️ Watch Locks',
    'hilo.poolStatusDanger': '🚨 Low Balance',
    
    // HiLoResults component
    'hiloResults.consumed': 'Spent',
    'hiloResults.won': 'Won',
    'hiloResults.gameHistory': 'Game History',
    'hiloResults.noHistory': 'No game history',
    'hiloResults.cashedOut': 'Cashed Out x{n}',
    'hiloResults.guessedWrong': 'Wrong x{n}',
    'hiloResults.credits': 'Credits',
    
    // FAQ extended
    'faq.title': '❓ FAQ',
    'faq.q1': 'Where did my tokens go?',
    'faq.a1': 'Tokens are burned to dead address, permanently reducing supply, not taken by anyone',
    'faq.q2': 'How long until prizes arrive?',
    'faq.a2': 'About 2-3 blocks (~10 seconds) after VRF confirmation, auto-delivered',
    'faq.q3': 'Why does it show "Waiting for VRF"?',
    'faq.a3': 'Chainlink VRF needs 2-3 blocks to confirm. Please wait. If over 1 hour, try canceling stuck request',
    'faq.q4': 'Can I get tokens back from credits?',
    'faq.a4': 'No. Credits can only be used for gaming, tokens are burned and irreversible',
    'faq.poolSource': '💰 Where does pool money come from?',
    'faq.poolSourceAnswer1': 'Prize pool funded by 3% of trading tax!',
    'faq.poolSourceAnswer2': 'Every token trade (buy/sell) generates tax, 3% goes to game pool for winners.',
    'faq.poolSourceNote': 'How it works: Tax → Auto-swap to BNB → Inject to pool contract',
    'faq.poolSourceTip': 'More trading = bigger pool = bigger prizes!',
    'faq.whyCredits': 'Why use credits instead of tokens directly?',
    'faq.whyCreditsAnswer': 'Credit system reduces on-chain transactions, saving gas. Exchange once, play many times, smoother experience.',
    'faq.higherBet': 'Higher bet really means higher odds?',
    'faq.higherBetAnswer': 'Yes! Higher bets increase rare symbol (7️⃣💎) appearance. 500K bet has 20x odds boost vs 20K, but bet responsibly.',
    
    // Payout table
    'payoutTable.title': 'Full Payout Table',
    
    // Footer
    'footer.onchain': 'On-Chain Mode | Smart Contract Connected',
    'footer.poweredBy': 'Powered by BNB Chain & Chainlink VRF',
    
    // Win overlay
    'win.prize': 'Prize Won',
    'win.clickToClose': 'Click anywhere to close',
    
    // WinDisplay
    'winDisplay.first': '👑 1st Prize 👑',
    'winDisplay.second': '🔔 2nd Prize 🔔',
    'winDisplay.third': '⭐ 3rd Prize ⭐',
    'winDisplay.small': '🍀 Small Win 🍀',
    'winDisplay.consolation': '🎁 Consolation 🎁',
    'winDisplay.paylines': '{n} paylines won',
    'winDisplay.poolPercent': 'Pool {n}%',
    'winDisplay.more': 'more',
    
    // CompactGameHistory
    'compactHistory.title': 'Recent Wins',
    'compactHistory.live': 'Live',
    'compactHistory.noRecords': 'No wins yet',
    'compactHistory.viewMore': 'View more →',
    
    // 404 Page
    'notFound.title': '404',
    'notFound.message': 'Page not found',
    'notFound.backHome': 'Return to Home',
    
    // Wallet
    'howToPlay.binanceWallet': 'Binance Wallet',
    
    // Audio controls
    'audio.mute': 'Mute',
    'audio.unmute': 'Unmute',
    'audio.bgMusicOn': 'Turn on background music',
    'audio.bgMusicOff': 'Turn off background music',
    
    // Auto spin
    'autoSpin.title': 'Auto Spin',
    'autoSpin.remaining': 'Auto',
    'autoSpin.stop': 'Stop',
    'autoSpin.selectCount': 'Select auto spin count',
    'autoSpin.times': 'x',
    'autoSpin.start': 'Start Auto',
    'autoSpin.hint': 'Click stop anytime',
    
    // Reward Tiers component
    'rewardTiers.title': 'Rewards & Payout Table',
    'rewardTiers.deflationTitle': '🎯 100% Burn | Zero Commission',
    'rewardTiers.deflationHighlight': '✨ Tokens 100% burned to dead address',
    'rewardTiers.deflationPoint1': 'Winnings: 95% to player, 5% VRF operation fee',
    'rewardTiers.deflationPoint2': 'No hidden fees, no platform commission',
    'rewardTiers.deflationPoint3': 'Smart contract transparent & verifiable',
    'rewardTiers.poolProtection': 'Pool Protection',
    'rewardTiers.maxPayout': 'Max single payout: Pool',
    'rewardTiers.zeroReserve': 'Pool funds 100% for prizes, zero reserve',
    'rewardTiers.levels': 'Reward Levels (Pool-based)',
    'rewardTiers.payoutNote': 'Actual payout = Pool × Percentage (capped at max limit)',
    'rewardTiers.betBonus': 'Bet Odds Bonus',
    'rewardTiers.winOdds': 'Win Odds',
    'rewardTiers.betTip': 'Higher bets increase rare symbol appearance',
    'rewardTiers.symbolRarity': 'Symbol Rarity',
    'rewardTiers.winConditions': 'Win Conditions (5-Symbol Match)',
    'rewardTiers.winConditionsNote': 'Wins based on matching symbol count in 5 symbols (~60% win rate)',
    'rewardTiers.condition.superJackpot': '5× 7️⃣',
    'rewardTiers.condition.jackpot': '5× 💎, or 4× 7️⃣',
    'rewardTiers.condition.first': 'Any 5 same symbols',
    'rewardTiers.condition.second': '4× same rare symbols (7️⃣💎👑🔔⭐)',
    'rewardTiers.condition.third': '4× same common symbols (🍒🍋🍊🍇🍀)',
    'rewardTiers.condition.small': 'Any 3 same symbols',
    'rewardTiers.condition.consolation': 'Any 2 same symbols (~45% odds)',
    'rewardTiers.displayNote': 'Result Display',
    'rewardTiers.displayDesc1': 'Slot shows 3 rows, but only the middle row (highlighted) is the actual result.',
    'rewardTiers.displayDesc2': 'Top and bottom rows are decorative, not used for wins.',
    'rewardTiers.vrfDesc': 'Uses Chainlink VRF for true random numbers, ensuring fair and unpredictable results. Each spin uses VRF request, result returns in ~2-3 blocks.',
  },
};

interface LanguageProviderProps {
  children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(() => {
    // 尝试从 localStorage 读取
    if (typeof window !== 'undefined') {
      const saved = localStorage.getItem('language');
      if (saved === 'zh' || saved === 'en') {
        return saved;
      }
    }
    return 'zh'; // 默认中文
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
